version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: .Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: .Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - backend
